### ISSUE TITLE
get_query_pool_results is not usable

### ISSUE THREAD

**Issue by kvark** [ash-rs/ash#100]
The signature of `get_query_pool_results` appear to be too high level: it requires the type known at compile time. If we are making a Vulkan wrapper, all we have is a run-time stride, we aren't able to provide that type.

**Comment by Ralith** [comment]
Can't you set `T = u8` and transmute from whatever?

**Comment by kvark** [comment]
I'm currently using the "raw" function from the function pointer instead of the wrapper. I guess this would be a canonical example of why gfx-hal needs to use ash-sys instead of ash.

**Comment by Ralith** [comment]
I would rather say it's an example of a correctable error in ash, given the explicit intention to expose things losslessly.

**Comment by MaikKlein** [comment]
Any idea how we should change the signature of `get_query_pool_results`? I assume we would have to fall back mut `&[u8]` + stride?

**Comment by Ralith** [comment]
That would be consistent with other parts of ash (e.g. `cmd_copy_buffer`), at least.

**Comment by MarijnS95** [comment]
@kvark is this still a problem in practice? We made the API a bit more clear by purely pulling the query count out of the slice length of `&mut [T]`, and using `sizeof<T>` for the *stride* (so that e.g. `WITH_AVAILABILITY` must be read using `T = (u64, u64)` for the stride and count to be correct). That doesn't solve your request of getting rid of the generic entirely, but it is seems niche enough to just call `(device.fp_v1_0().get_query_pool_results)(...).result()?;` as you seem to have done in https://github.com/gfx-rs/gfx/pull/2334/files#diff-8b40610d6c5dc2e96f8f2a27e56d606238ed61c1370bfd632ffd20117b4f2a58.

**Comment by MarijnS95** [comment]
Closing as stale.
