### ISSUE TITLE
Move ash to a separate organization

### ISSUE THREAD

**Issue by MaikKlein** [ash-rs/ash#586]
Ash has been around for quite some time, and while it started as a personal project it has accumulated a few maintainers now.
I'd like to reflect that and move ash to an organization. This should also make it easier to give our maintainers full access to the repo.

* What should we name the org? `ash-rs`?
* Should we use an existing org? (I don't think so, but I want to bring it up)
* Any possible problems we will run into? 
* * Need to update links in the readme
* * ...
* Any concerns about this in general?

Ping @MarijnS95 @Ralith

**Comment by Ralith** [comment]
> `ash-rs`

Seems fine to me!

> Should we use an existing org? (I don't think so, but I want to bring it up)

We could move it to `rust-gamedev`, which has the advantage that if we all die in a plane crash, a reasonably sane third party will still have access. Personally I think we already have enough maintainers that this isn't compelling, though.

**Comment by MarijnS95** [comment]
I think our own org is more convenient, `ash-rs` seems like the perfect choice for it. We could also move under @Traverse-Research but it's just me for now so a new orga seems like the fairest ground.

Not too worried about any of the other changes, nor all of us suddenly disappearing at once.

With that it might also be a good idea to set up crates.io publish secret keys [like android-ndk-rs](https://github.com/rust-windowing/android-ndk-rs/blob/master/.github/workflows/publish.yml) so that maintainers can simply push/merge version bumps to trigger an automated publish workflow. Not everyone needs a to be manually granted access that way, though OTOH this may still be useful if a version needs to be yanked (fortunately never happened yet :crossed_fingers:) or other crates.io maintenance has to occur.

**Comment by MaikKlein** [comment]
I just created a new org `ash-rs` and invited you. If there are no objections, I'll do the transition this weekend.

**Comment by MarijnS95** [comment]
@MaikKlein Thanks! I think GitHub automatically sets up a redirect when transferring a repository, which afaik keeps working as long as you don't create a repo with the same name in your user account.

**Comment by MaikKlein** [comment]
I just moved ash to `ash-rs`. I also made you both owners in the new org @MarijnS95 @Ralith.

**Comment by MarijnS95** [comment]
Awesome, thanks @MaikKlein! I immediately made two config changes: enabled `Always suggest updating pull request branches` and `Automatically delete head branches` :slightly_smiling_face:
