### ISSUE TITLE
Bad Vulkan docs links on hover-info 

### ISSUE THREAD

**Issue by ArrowMaxGithub** [ash-rs/ash#636]
### Info:
ash - 0.37.0
VSCode - 1.68.0

### Issue: 
When hovering over an item in VSCode, the displayed Vulkan docs link is bad.

### Example vkCreateFramebuffer:
Instead of 
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateFramebuffer.html

The info box lists 
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateFramebuffer.html](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateFramebuffer.html)

![image](https://user-images.githubusercontent.com/60489413/173220133-901d5604-54b8-41f5-a12e-117fd5f90375.png)

### Workaround:
Ctrl-click the item in VSCode to get to the source implementation.
Ctrl-click the correct link above the function.
![image](https://user-images.githubusercontent.com/60489413/173220591-d26cc28e-cf35-461f-8031-28a9e916d69f.png)

It's a very minor thing, but a nice-to-have for future releases.

**Comment by MarijnS95** [comment]
> but a nice-to-have for future releases.

Since you filed this issue in the `ash` repo, what exactly do you expect us to do about it? [`autolinks` are part of the markdown specification](https://daringfireball.net/projects/markdown/syntax#autolink), and they [render correctly on docs.rs](https://docs.rs/ash/latest/ash/struct.Device.html#method.create_framebuffer). If anything this is a bug in either VSCode or - more likely - `rust-analyzer` which is afaik responsible for pulling out these doc comments, resolving/rendering them (e.g. for intradoc links that don't yet work), and finally providing the resulting html VSCode intellisense. Unless VSCode is badly post-processing the link?

Alas, not something I think we can help with, and probably not strictly isolated to this `ash` crate either :sweat_smile:

**Comment by ArrowMaxGithub** [comment]
Thanks!
I wrongly assumed this was an issue with ash.

I'll cross-check if other links from other crates show this behaviour as well and close this issue/refile it with VSCode in that case.
