### ISSUE TITLE
`get_query_pool_results` buggy when called with `vk::QueryResultFlags::WITH_AVAILABILITY`

### ISSUE THREAD

**Issue by matszczygiel** [ash-rs/ash#639]
Hello,
I have a piece of code which according to my knowledge does not violate the Vulkan spec.
```rust
let first_query = 0;
let query_count = 2;
let flags = vk::QueryResultFlags::WITH_AVAILABILITY;
let mut data = [0u32; 4];
device.get_query_pool_results(
    query_pool,
    first_query,
    query_count,
    data.as_mut_slice(),
    flags,
)?;
```
This code gives a validation error:
```
[VK][Validation]"Validation Error: [ VUID-vkGetQueryPoolResults-dataSize-00817 ] Object 0: handle = 0x13105e0000000155, type = VK_OBJECT_TYPE_QUERY_POOL; | MessageID = 0x73375ed4 | vkGetQueryPoolResults() on querypool VkQueryPool 0x13105e0000000155[] specified dataSize 8 which is incompatible with the specified query type and options. The Vulkan spec states: dataSize must be large enough to contain the result of each query, as described here (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkGetQueryPoolResults-dataSize-00817)"
```

I managed to locate a bug in the implementation of this function. It passes `query_count` as a data length parameter forward. This is fine in most cases but here the flag`vk::QueryResultFlags::WITH_AVAILABILITY` requires the data to be twice as large as `query_count`.
I will open PR with a fix.

**Comment by MarijnS95** [comment]
This ended up not requiring a fix but merely a simplified API since the type `T` of `data: &[T]` is used to determine the stride, where `T = u32` for a `WITH_AVAILABILITY` query would overwrite the bool in query `N-1` which was _not_ addressed by the linked PR. Instead we now force the user to use slice length by removing the `query_count` value:  https://github.com/ash-rs/ash/pull/644

This is a breaking change that has not been released yet (will be part of Ash 0.38) but to achieve what you want now, make sure `T` includes the availability flag through a tuple via `T = (0u32, vk::Bool32)`, and request a total of 2 instead of 4 queries:


```rust
let first_query = 0;
let query_count = 2;
let flags = vk::QueryResultFlags::WITH_AVAILABILITY;
let mut data = [(0u32, vk::Bool32); query_count];
device.get_query_pool_results(
    query_pool,
    first_query,
    data.len(),
    data.as_mut_slice(),
    flags,
)?;
```
