### ISSUE TITLE
Allow validation errors to trigger for non deallocated objects.

### ISSUE THREAD

**Issue by Makogan** [ash-rs/ash#652]
This entire time I was working on the assumption ash implemented drop for all objects, similar to how vulkan.hpp works. My program was behaving weirdly and if I am correct, no object in ash actually implements drop.

This is not a huge problem in and of itself, but my program does not trigger any validation layers on termination. So I have dozens upon dozens of memory leaks and no mechanism to find them.

If ash doesn't want to take the responsibility of keeping track of the objects, it would be very useful to get the validation errors one gets when he forgets to free memory on program termination. 

Right now the program terminates without raising any warnings. It's fine if ash doesn't deallocate automatically, but it is not fine it seems to free resources before the validation layers can warn the user of a memory leak.

this is partially related to:
https://github.com/ash-rs/ash/issues/624

**Comment by SparkyPotato** [comment]
The validation layers only output errors when the 'owning' object (instance, device, etc.) is destroyed. This is because it is not undefined behavior to leave everything alive.

If you were to destroy your instance and device, you would see all the errors.

This has nothing to do with ash, since it doesn't destroy objects until you tell it to.
