### ISSUE TITLE
Deprecation notice of VkDeviceCreateInfo enabledLayerCount and ppEnabledLayerNames 

### ISSUE THREAD

**Issue by charles-lunarg** [ash-rs/ash#670]
(apologies for using the C structure names)

Recently had a user try to enable validation layers through the device. This does nothing, and makes users that are unaware of its uselessness think they are enabling validation.

Maybe it isn't possible, but it would be lovely if there was a 'deprecated' tag for this.

**Comment by Ralith** [comment]
Sounds reasonable to me!

**Comment by MarijnS95** [comment]
@charles-lunarg good catch, thanks for bringing this to our attention!

Both the structure and builder are automatically created by our generator; while we can hack in a workaround for these specific fields it'd be much better if `vk.xml` provides a standard way to communicate this.

For misnamed enum variants for example we currently scan for `comment="Backwards-compatible alias containing a typo"` and ignore those variants entirely (because we're not able to generate a proper shortened name for it). Perhaps a similar `comment` attribute could be set for these fields (doesn't seem the case on `1.3.231` yet), or even a more appropriate `deprecated=` attribute?

For reference, in Rust we have:

```rust
#[deprecated = "Friendly message shown to the user"]
```

This friendly message allows us to explain why something was deprecated, and/or what the alternatives are - we can propagate a useful message directly from `vk.xml` :slightly_smiling_face:

**Comment by MarijnS95** [comment]
@charles-lunarg any updates here?

**Comment by charles-lunarg** [comment]
The WG is unlikely to create a solution deprecation notices anytime soon, so I see two ways to resolve this github issue.
1. Close it as wont-fix, due to preferring a explicit `vk.xml` tag so that all cases can be handled
2. Hack it in just for this case.

I'm in the 2. camp due to wanting to prevent users from making preventable mistakes, but as I am not the maintainer, that is just my opinion.

Better to have a fix now rather than possibly wait 1-2 years to get a vk.xml change.

**Comment by MarijnS95** [comment]
I'm fine with 2. as long as we've explored that 1. isn't viable "because upstream™", though I'd still like to push for such a notice sooner rather than later. Even if they don't create official deprecation notices, a `comment=` to that effect would allow us to already treat it as official, please keep pushing to that effect!

Feel free to make PR that adds the suggested deprecation notice above, or I can do it for you.

**Comment by MarijnS95** [comment]
That link specifically seems to concern deprecated/superseded extensions, while we're dealing with deprecated fields (and deprecated-but-maintained-for-backwards-compatibility aliases for broken names). Would be great if both could get a `deprecated="Reason"` (in favour of having to "parse" that out from the `comment=` field as mentioned above).

**Comment by charles-lunarg** [comment]
Ah right, extensions being deprecated is different than members of structs. 

I think it actually shouldn't be too hard to get buy in for a `deprecated=` for the struct members in question. I'll propose that in an internal PR. May be a while before it is released, but I'll try to update this issue with its status. (including if it gets summarily closed)

**Comment by MarijnS95** [comment]
Thanks! Feel free to ping me there too.

**Comment by MarijnS95** [comment]
@charles-lunarg see https://github.com/ash-rs/ash/pull/697; the new `deprecated` property is already put to use and we'll be able to merge that PR after integrating the new `api` property too to filter out SC members/definitions etc.

**Comment by MarijnS95** [comment]
@charles-lunarg #697 now also takes care of generating `#[deprecated]` annotations on these fields :tada: 

As mentioned many times before the generator is getting messier and messier, but we're working on a replacement so don't look too much into the current monstrosity. Do however check if its outputs match your expectation though!

**Comment by charles-lunarg** [comment]
Looks good to me! Thanks for working on making this change happen in vk.xml, seems like it was a good spot of clean up all around to boot.

**Comment by MarijnS95** [comment]
It was!

Just noticing now though that we didn't drop _one_ deprecated enum alias for `VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE` on the last breaking Ash release (when we dropped everything else because it just made no sense to let the generator come up with sensible names for them, only to annotate it with `#[deprecated]` pointing to the right member because it's a warning by default that no-one would ever use), meaning I have to make an exemption for it when backporting this to `0.37` :(
