### ISSUE TITLE
FYI - we will be making use of 'api' attribute in Vulkan XML, you will need a small change

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#698]
This has been part of the schema for a while, but we will start using it soon to allow combining the Vulkan and Vulkan SC XML in a single file. You will need to adapt your loading code to this new use.

The simplest way is to globally pre-filter the XML to remove all tags with explicit 'api' elements not matching the API being generated, as the Vulkan-Docs scripts already do. For this you can either use the scripts/stripAPI.py script that's provided, or do the equivalent

> import reg  
> keepAPI = 'vulkan'
> reg.stripNonmatchingAPIs(tree.getroot(), keepAPI, actuallyDelete=True)

after loading your ElementTree from the XML, where 'reg' is scripts/reg.py from the Vulkan-Docs repository. Although since you are probably doing the loading and parsing in Rust, you would have to figure out the equivalent of this Python command. The essence is to recursively traverse the XML tree removing any tags with explicit non-matching 'api' attributes at the point they're encountered, prior to any other XML parsing.

Let me know if there are any questions. There isn't a specific timescale for this, but probably will appear starting sometime in February.

**Comment by MarijnS95** [comment]
Part of this may have to come from `vk_parse`, cc @krolli.

**Comment by oddhack** [comment]
FYI, the XML changes have been published in Vulkan-Docs in the v1.3.241 tag.

**Comment by MarijnS95** [comment]
Yup, seen that @oddhack, thanks! I've started processing the new `deprecated` field at #697 (pending https://github.com/krolli/vk-parse/pull/28) which hampered regeneration and will now shift to processing the new `api` attribute which is only causing miscompilation (duplicate fields).

**Comment by MarijnS95** [comment]
@oddhack I'm currently implementing this and `VKSC_API_VARIANT` and `VKSC_API_VERSION_1_0` are missing `api="vulkansc"`, is that intentional?

**Comment by MarijnS95** [comment]
@oddhack right, only `VK_HEADER_VERSION`/`VK_HEADER_VERSION_COMPLETE` have these but to be used as an if-else.

Unfortunately Ash's generator doesn't look at these dependencies and emits any `<type>` it sees. While we do have similar "tagging" via a bunch of hashsets that are passed all over the place, it's really messy and error-prone. We can probably work our way around this with more hashsets, but should really push on rewriting/restructuring it to make this a first-class citizen.

**Comment by oddhack** [comment]
I recommend something like what the Python scripts do - first pass sweeps up all the interfaces in the XML into dictionaries (hashes, whatever), second figures out which are required by recursive dependency tagging, third emits the required interfaces.

**Comment by MarijnS95** [comment]
Yup that's exactly what we want (CC #344 #662 and more) but just haven't gotten to it yet. For now the generator is mixing both this so-coined "analysis" stage (doing more than just sweeping up `depends=`) and codegen stage.

**Comment by MarijnS95** [comment]
PR is now once again updated, this time with hopefully all the `api` fields on all the various elements covered.

**Comment by oddhack** [comment]
This is forward looking, but I realized that we were using the 'api' attribute on XML \<feature> tags inconsistently from the rest of the schema (because the first use dates all the way back to OpenGL's schema), which is causing some issues for Vulkan SC. So I am suggesting a change there (see gitlab vulkansc MR 339) to replace the \<feature> 'api' attribute with 'supported', just like \<extension> tags. Not clear this would actually impact you at all and it will be some time until it's merged into Vulkan main if we do decide to pursue it, but FYI.

**Comment by MarijnS95** [comment]
@oddhack that may have been, I did indeed notice in #697 that `<extension>` already used `supported="vulkan"` for the longest time to convey the value that is nowadays stored in the `api` field:

https://github.com/ash-rs/ash/blob/31dca5157165e9a521079307f82e9be804ede053/generator/src/lib.rs#L2702-L2708

(Perhaps because another allowed value is `"disabled"`, which isn't technically an API?)

We'd have to update `vk-parse` and our generator once again, but nothing major as we're updating in lockstep with `Vulkan-Headers` anyway.

**Comment by MarijnS95** [comment]
@oddhack so summarizing vulkansc MR 339 in the way that I grasp it: the `api` attribute was still using old OpenGL docs and its meaning was never updated for Vulkan, so the contents of that field were never properly described, so you've opted to just switch over to `supported` to force consumers to look at the docs rather than changing the semantics of `api`, while also making `<feature>` look more closely like `<extension>`?

**Comment by oddhack** [comment]
Yes (once the docs themselves are actually updated, which that MR doesn't yet do).

**Comment by oddhack** [comment]
> (Perhaps because another allowed value is "disabled", which isn't technically an API?)

"disabled" isn't a special value. It's just a value that is not a valid API name, used as a placeholder on extension reservations that don't yet have the actual extension defined. It should behave the same with a value of "xyzzy" because in practice people ask for the 'vulkan' or 'vulkansc' APIs to be generated, not the 'disabled' or 'xyzzy' APIs.

**Comment by MarijnS95** [comment]
> It should behave the same with a value of "xyzzy" because in practice people ask for the 'vulkan' or 'vulkansc' APIs to be generated, not the 'disabled' or 'xyzzy' APIs.

Sounds good, we do that now since #697...

https://github.com/ash-rs/ash/blob/31dca5157165e9a521079307f82e9be804ede053/generator/src/lib.rs#L2707-L2708

But looked specifically for "not disabled" before :)

https://github.com/ash-rs/ash/blob/eaf140fcb0be0ff63f7dcee2b96eee0ee5ebaf1d/generator/src/lib.rs#L2555
