### ISSUE TITLE
seg faulting from cmd_begin_debug_utils_label 

### ISSUE THREAD

**Issue by AlecGoncharow** [ash-rs/ash#700]
Hello!

This is likely a bug with my machine's driver, as mentioned in https://github.com/ash-rs/ash/issues/484, but just to exhaust all options: 

While attempting to run a project of mine on a new machine, I ran into a segmentation fault that starts with a call to https://docs.rs/wgpu/latest/wgpu/struct.RenderPass.html#method.push_debug_group 

Stepping through this I ended up with the following:

```
wgpu_hal::vulkan::command::{impl#2}::begin_debug_marker (self=0x555557401e78, group_label="global_light_shadow_1") at src/vulkan/command.rs:527
527                ext.cmd_begin_debug_utils_label(self.active, &vk_label);
(gdb) s
ash::extensions::ext::debug_utils::DebugUtils::cmd_begin_debug_utils_label (self=0x555557001500, command_buffer=..., label=0x7fffffec1590) at /home/algo/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.37.2+1.3.238/src/extensions/ext/debug_utils.rs:71
71            (self.fp.cmd_begin_debug_utils_label_ext)(command_buffer, label);
(gdb) s

Thread 1 "game-client" received signal SIGSEGV, Segmentation fault.
0x00007fffb78037d3 in ?? () from /usr/lib/libvulkan_intel.so
```
This is the second call to this function, after popping the previous label. 

My `vulkaninfo` output: https://gist.github.com/AlecGoncharow/7904afdc730159b40a2e26e494e2be60

**Comment by MarijnS95** [comment]
> This is likely a bug with my machine's driver, as mentioned in https://github.com/ash-rs/ash/issues/484

Have you validated that the loaded function pointer in question - `cmd_begin_debug_utils_label_ext` - is NULL? Since you end up at a non-null address in the driver, that's likely to be a different issue.

However, the last comment there reports on a _different_ issue, namely the address NOT being null but pointing to a driver function that segfaults internally. Can you provide a similar dump/disassembly? And since `libvulkan_intel` should come from Mesa, recompile the driver with debug symbols first? (and/or make sure debug symbols are available on your flavour of distro).

**Comment by MarijnS95** [comment]
Closing this after not receiving any followup, there appears to be nothing actionable for `ash`.
