### ISSUE TITLE
Gitlab CI is failing on ash-generate stage while Github succeeds

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#721]
Per #698. It seemed to fix one CI but not the other. gitlab is [failing in the ash-generate step](https://gitlab.khronos.org/vulkan/vulkan/-/jobs/394605) with 'error[E0658]: `let...else` statements are unstable'. I wonder if they're running different versions of rust or like that, since github appears to be running in a regular ubuntu image while gitlab is using the khronosgroup/docker-images:rust image ? N.b. both gitlab and github I have found to be utterly useless when it comes to recognizing that the named image has been updated and not relying on an out of date cached version, and so I now use image SHAs instead for the spec-building images, annoying though that is to keep track of and update.

**Comment by MarijnS95** [comment]
The docker image for GitLab must've been built quite some time ago, when we first added Ash to the CI. Since it [always pulls latest](https://github.com/KhronosGroup/DockerContainers/blob/8517e6cbeec4dda1866dad4d86167e44d2ccb370/rust.Dockerfile#L7) this should easily be solvable by rebuilding the container and using the new hash.

We generally try to stay away from eagerly requiring the latest Rust version for the `ash` crate, but usually rely on the latest features in the generator which is only used by a handful number of people and in our controlled CI environment (and now also the Khronos CI environment). Unfortunately certain downstream dependencies (for the `ash-window` crate, fortunately `ash` only has one optional dependency) bump their minimum required Rust version when it has been available for ~6 months, and publish those as non-breaking semver change causing similar troubles.

> N.b. both gitlab and github I have found to be utterly useless when it comes to recognizing that the named image has been updated and not relying on an out of date cached version, and so I now use image SHAs instead for the spec-building images, annoying though that is to keep track of and update.

GitHub at least is very clear on what their images contain, and what percentage of users it got rolled out to. One can lock to a specific Ubuntu version, but unfortunately [nothing is said about what yaml label to use](https://github.com/actions/runner-images#available-images) to get a specific tagged release.

**Comment by oddhack** [comment]
Updating the image and pulling by SHA did indeed fix this problem on gitlab - thanks!

> GitHub at least is very clear on what their images contain, and what percentage of users it got rolled out to. One can lock to a specific Ubuntu version, but unfortunately [nothing is said about what yaml label to use](https://github.com/actions/runner-images#available-images) to get a specific tagged release.

I don't think it's an issue with github-provided images - it's custom containers that suffer caching problems. I believe the way the ash CI is setup, it uses the khronosgroup 'rust' image on gitlab but github's ubuntu image there.
