### ISSUE TITLE
Unable to load cmd_pipeline_barrier2

### ISSUE THREAD

**Issue by NickDriscoll** [ash-rs/ash#729]
When I call cmd_pipeline_barrier2(), I get a panic with the message in the title.

I'm using ash::Entry::linked(), I'm on the most recent Windows Vulkan SDK from LunarG, and I query for sync2 features with get_physical_device_features2() and pass the approriate structures to the device creation's p_next chain.

Is sync2 available in ash?

**Comment by MarijnS95** [comment]
> Is sync2 available in ash?

Ash only provides the Rust bindings/wrappers. If you're using it in your Rust code, it's there and supported.

---

Did you make sure to enable Vulkan 1.3 for your app, otherwise you cannot load Vulkan 1.3 functions? Alternatively, enable and try the `Synchronization2` extension.

**Comment by Ralith** [comment]
You must *enable* features you want to use, not just query them.

**Comment by NickDriscoll** [comment]
I do have Synchronization2 in my pp_enabled_extension_names. I also pass &physical_device_features.features to &physical_device_features.features, so my logical device should be getting created with all the features.

**Comment by NickDriscoll** [comment]
So with absolutely no code changes, when I tried running my program today it just worked. Maybe I had to restart my PC for some reason? I truly don't know, like I said it's the exact same device creation code.

**Comment by NickDriscoll** [comment]
Honestly this just makes it more confusing because I create a Vulkan 1.2 instance (at least I do vk::make_api_version(0, 1, 2, 0)), and I am loading the Sync2 extension, but it's true that I'm calling the wrong function without the khr suffix. Really not sure how this is all possible. For what it's worth, switching to the function provided by the extension also works just fine when I try it. (though not named what you said, it's ash::extensions::khr::synchronization2::Synchronization2::cmd_pipeline_barrier2 no suffix)

**Comment by MarijnS95** [comment]
> Honestly this just makes it more confusing because I create a Vulkan 1.2 instance (at least I do vk::make_api_version(0, 1, 2, 0)), and I am loading the Sync2 extension, but it's true that I'm calling the wrong function without the khr suffix. Really not sure how this is all possible.

That's how Vulkan works for you. Prior to Vulkan 1.3 this function was only available through an extension, and you had to enable the extension _and_ load the `_khr`-suffixed extension function. Now that it is stabilized you have to load the non-`_khr`-suffixed version, but the driver sanity _only makes it available when your app advertises 1.3 compatibility_.

Ash being a low-level bindings wrapper means we will do nothing to hide this behaviour from the user.

> For what it's worth, switching to the function provided by the extension also works just fine when I try it.

Yeah that makes a lot of sense, you now enable 1.2, the extension, and use the extension. Alternatively you can switch to advertising 1.3, remove the extension (but keep the feature enablement), and call the non-`_khr` function: that is up to you based on the target hardware/drivers you intend to support in your application.

> (though not named what you said, it's ash::extensions::khr::synchronization2::Synchronization2::cmd_pipeline_barrier2 no suffix)

It definitely is, the loader struct is reexported from the `khr` module at `ash::extensions::khr::Synchronization2`:


https://github.com/ash-rs/ash/blob/f98cab47ddc9a882a8a2fc6858b1a5d64a467151/ash/src/extensions/khr/mod.rs#L32

The function calls the `_khr` version, but we strip those suffixes off of it because it is already encoded in the namespace higher up:

https://github.com/ash-rs/ash/blob/f98cab47ddc9a882a8a2fc6858b1a5d64a467151/ash/src/extensions/khr/synchronization2.rs#L22-L27

**Comment by NickDriscoll** [comment]
What I am saying is that it's working in 1.2 with the extension _despite_ the fact that I'm using the 1.3 non-extension function. That is specifically what I am confused about here now.

**Comment by MarijnS95** [comment]
@NickDriscoll that's indeed odd, I thought you said in https://github.com/ash-rs/ash/issues/729#issuecomment-1490461037 that it started working on 1.2 (plus enabling the extension) _after_ switching to the extension function. Are you saying thhat it is now also working with `ash::Device::cmd_pipeline_barrier2` despite setting 1.2 and _not_ `1.3` in `ApplicationInfo::api_version`.

**Comment by XavierCS-dev** [comment]
I was having this same issue, even when requesting the extensions, however in my application info requesting vulkan 1.3 fixes the issue.

**Comment by MarijnS95** [comment]
@XavierCS-dev as explained above, when enabling the extension without Vulkan 1.3, did you use the `khr`-suffixed extension wrapper via `ash::(extensions::)khr::synchronization2::...::cmd_pipeline_barrier2()`, instead of the 1.3-stabilized `ash::Device::cmd_pipeline_barrier2()`?

**Comment by XavierCS-dev** [comment]
> @XavierCS-dev as explained above, when enabling the extension without Vulkan 1.3, did you use the `khr`-suffixed extension wrapper via `ash::(extensions::)khr::synchronization2::...::cmd_pipeline_barrier2()`, instead of the 1.3-stabilized `ash::Device::cmd_pipeline_barrier2()`?

No I was using the stabilised one.
