### ISSUE TITLE
How do you return filled out p_next'd structs?

### ISSUE THREAD

**Issue by codecnotsupported** [ash-rs/ash#757]
Consider the following example:
```rust
unsafe fn get_device_properties(instance: &Instance, physical_device) -> Result<(PhysicalDeviceProperties2, PhysicalDeviceDescriptorBufferPropertiesEXT)> {
    let mut descriptor_buffer_properties = PhysicalDeviceDescriptorBufferPropertiesEXT::default();
    let mut properties = PhysicalDeviceProperties2::default()
    .push_next(&mut descriptor_buffer_properties);

    vulkan_instance.get_physical_device_properties2(physical_device, &mut properties);

    Ok(properties, descriptor_buffer_properties)

}
```
The above code errors because `descriptor_buffer_properties` is owned by the function. 
And you can't Box `PhysicalDeviceDescriptorBufferPropertiesEXT` because there isn't a `from` impl, otherwise you'd need to borrow mutably which is the same situation as without box.

**Comment by codecnotsupported** [comment]
> Fortunately `PhysicalDeviceProperties2` is just a combination of `PhysicalDeviceProperties` and an `sType`/`pNext`, so you _might_ be able to return `Ok((properties.propertties, descriptor_buffer_properties))` instead?

`Ok((properties.propertties, descriptor_buffer_properties))` works, thanks.

> This lifetime issue however becomes a problem again when you start to chain more than one struct.

I added another `PhysicalDeviceDescriptorBufferPropertiesEXT` and it still worked fine. Both structs were filled in just fine.

Closing as the issue is resolved.

**Comment by Ralith** [comment]
Yeah, if you're careful not to traverse the pointers yourself, returning the filled-in structs is perfectly fine.

It's interesting to note that this will break in the upcoming release due to stronger lifetime tracking. The lifetime can be explicitly erased with constructions like `vk::PhysicalDeviceProperties2 { _marker: PhantomData, ..x}`, which is a little non-obvious.

**Comment by codecnotsupported** [comment]
> It's interesting to note that this will break in the upcoming release due to stronger lifetime tracking

Odd no breakage and I'm using the master branch of Ash is the upcoming release in there or another branch?
> The lifetime can be explicitly erased with constructions like vk::PhysicalDeviceProperties2 { _marker: PhantomData, ..x}, which is a little non-obvious.

Thanks, I will keep that in mind the next time I find my compiler logs turn red after a update.

**Comment by Ralith** [comment]
That is odd. `push_next` *should* be causing `properties` to have a lifetime bounded by that of the borrow from `descriptor_buffer_properties` on the stack.

**Comment by MarijnS95** [comment]
@Ralith yeah given the example uses `::default()` instead of `::builder()` I'm sure @codecnotsupported is on the `master` branch with the latest struct-lifetime changes.

> That is odd. `push_next` _should_ be causing `properties` to have a lifetime bounded by that of the borrow from `descriptor_buffer_properties` on the stack.

Only if `properties2` is returned. The `properties` member of `vk::PhysicalDeviceProperties2` does not have a `p_next` field nor a lifetime.

---

With the above example fixed to make it compile and return the non-2 `vk::PhysicalDeviceProperties` struct, we also have a nontrivial lifetime on the way `push_next` injects **within** the pointer chain. In the following example we get a chain of `properties -> descriptor_buffer_properties -> another_descriptor_buffer_properties`, but we can safely return `descriptor_buffer_properties` with that dangling stack-pointer to `another_descriptor_buffer_properties`.

```
unsafe fn get_device_properties(
    instance: &Instance,
    physical_device: vk::PhysicalDevice,
) -> ash::prelude::VkResult<(
    vk::PhysicalDeviceProperties,
    vk::PhysicalDeviceDescriptorBufferPropertiesEXT,
)> {
    let mut another_descriptor_buffer_properties =
        vk::PhysicalDeviceDescriptorBufferPropertiesEXT::default();
    let mut descriptor_buffer_properties =
        vk::PhysicalDeviceDescriptorBufferPropertiesEXT::default();

    let mut properties = vk::PhysicalDeviceProperties2::default()
        .push_next(&mut another_descriptor_buffer_properties)
        .push_next(&mut descriptor_buffer_properties);

    instance.get_physical_device_properties2(physical_device, &mut properties);

    Ok((properties.properties, descriptor_buffer_properties))
}
```

**Comment by Ralith** [comment]
> Only if properties2 is returned. The properties member of vk::PhysicalDeviceProperties2 does not have a p_next field nor a lifetime.

Sure, but their example is returning the whole `vk::PhysicalDeviceProperties2`.

> we also have a nontrivial lifetime on the way push_next injects within the pointer chain

I see: we never actually constrain the lifetimes of non-root elements of the pointer chain; we only require that each individual chain element outlives the root. Once the root is dropped, all other chain pointers can be freely invalidated, which isn't really in the spirit of the lifetime annotation, though it happens to be convenient in this case. That's also why the original example is able to return `PhysicalDeviceDescriptorBufferPropertiesEXT`.

I think we can fix this by adding a lifetime parameter to the `Extends...` traits, through which we enforce that the lifetime of each pointer chain element is constrained to the lifetime of each element's borrow ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1da6613b13b68e046158987f6ad33f58)). This is a little bit circular but seems to work as intended.

That does put us face to face with the ergonomic problem of storing/returning these structures, though. I wonder if we should provide a `fn unlink(self) -> Foo<'static>` that zeroes the pointers or something?

**Comment by Ralith** [comment]
Wait, no, the example above is unusable since the non-root elements are permanently mutably borrowed...

**Comment by Ralith** [comment]
On further consideration, I think we can't easily express pointer chains with Rust lifetimes at all, since the p_next links are intrinsically mutable borrows, but we want to be able to access each element without painstakingly dropping all the earlier elements in the chain. Maybe the current behavior is the best we can hope for? It would be very unusual to follow links starting at a non-root element of a pointer chain, after all. We should at least carefully document that only the root's lifetime is enforced.

**Comment by MarijnS95** [comment]
> > Only if properties2 is returned. The properties member of vk::PhysicalDeviceProperties2 does not have a p_next field nor a lifetime.
> 
> Sure, but their example is returning the whole `vk::PhysicalDeviceProperties2`.

They [got it working](https://github.com/ash-rs/ash/issues/757#issuecomment-1564228215) after applying that (use `vk::PhysicalDeviceProperties2::properties`) suggestion, regardless of the `master` branch.

---

Regarding the rest, yes it seems to be nontrivial to track the individual mutable lifetime borrows of `p_next` chains unless we change how the current system works.

Regardless, it's still a raw pointer and dereferencing it is `unsafe`; this is where the user will have to do their own "validation" to ensure the pointer is still valid, within the spirit of "ash being a mostly low-level wrapper".

**Comment by Ralith** [comment]
Yeah, I think the status quo is good behavior-wise, but since now have *most* pointers lifetime-tracked if(!) you use our setters, it bears documenting that p_next is a special case.

**Comment by MarijnS95** [comment]
Yeah sure; since you're more fluent with wording, would you mind opening a PR for that?

In the example above it is something along the lines of not being able to tell the compiler that `another_descriptor_buffer_properties` got "mutably borrowed" (via a raw pointer) by `descriptor_buffer_properties` when it was passed through `properties.push_next()`.
