### ISSUE TITLE
No way to get the surface scaling capabilities

### ISSUE THREAD

**Issue by vityafx** [ash-rs/ash#793]
[get_physical_device_surface_capabilities2](https://docs.rs/ash/latest/ash/extensions/khr/struct.GetSurfaceCapabilities2.html#method.get_physical_device_surface_capabilities2) Has no way to specify the `p_next` chain with the objects desired. Currently, the ash code implementing this functionality doesn't make use of the possibility of user-defined objects included in the `p_next` chain. It relies on the `Default::default()` implementation, which returns almost (if not the same) object as if the first version of this function:

```rust
    /// <https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceSurfaceCapabilities2KHR.html>
    #[inline]
    pub unsafe fn get_physical_device_surface_capabilities2(
        &self,
        physical_device: vk::PhysicalDevice,
        surface_info: &vk::PhysicalDeviceSurfaceInfo2KHR,
    ) -> VkResult<vk::SurfaceCapabilities2KHR> {
        let mut surface_capabilities = Default::default();
        (self.fp.get_physical_device_surface_capabilities2_khr)(
            physical_device,
            surface_info,
            &mut surface_capabilities,
        )
        .result_with_success(surface_capabilities)
    }
```
I can't understand the intention behind this code, as I believe this function (`get_physical_device_surface_capabilities2_khr`) is intended to be used with the surface_capabilities object **with** something else being included in the `p_next` chain.

Would it make sense to rewrite this function so that it actually accepts the object from the user instead, and it becomes the user's responsibility to fill whatever is needed?

```rust
    /// <https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceSurfaceCapabilities2KHR.html>
    #[inline]
    pub unsafe fn get_physical_device_surface_capabilities2(
        &self,
        physical_device: vk::PhysicalDevice,
        surface_info: &vk::PhysicalDeviceSurfaceInfo2KHR,
        surface_capabilities: &mut vk::SurfaceCapabilities2KHR,
    ) -> VkResult<vk::SurfaceCapabilities2KHR> {
        (self.fp.get_physical_device_surface_capabilities2_khr)(
            physical_device,
            surface_info,
            &mut surface_capabilities,
        )
        .result_with_success(surface_capabilities)
    }
```

I think I have already seen similar APIs, and how Ash handled those was okay. I think it was somewhere in the physical device properties area. I guess this particular piece would also be nice if done this way.

**Comment by MarijnS95** [comment]
This was already solved (in almost the same way as proposed, except with the returned object removed because we can no longer move it; the suggestion wouldn't compile) in #744.

Unfortunately the nature of such changes is _breaking_, and we're not there yet to release the next breaking/major version of Ash until resolving some other big-surface-area problems. But those are taking more time than anticipated.

For the time being you could either depend on the (`rev`-fixed) `master` version of this repo to have access to the fix, or - because the implementation is so trivial - manually call the low-level function pointer by acquiring the loaded function-pointer-object via `(xxx.fp().get_physical_device_surface_capabilities2_khr)(physical_device, surface_info, &mut surface_capabilities)`.
