### ISSUE TITLE
Segfault in opt level 3.

### ISSUE THREAD

**Issue by mqxf** [ash-rs/ash#886]
Here is the code that is breaking:
```rust
    pub(crate) fn begin_render_pass(
        &self,
        command_buffer: &VkCommandBuffer,
        clear_colors: &[ClearColor],
        extent: ash::vk::Extent2D,
    ) {
        let viewport = [ash::vk::Viewport::builder()
            .x(0.0f32)
            .y(0.0f32)
            .width(extent.width as f32)
            .height(extent.height as f32)
            .min_depth(0.0f32)
            .max_depth(0.0f32)
            .build()];

        let scissors = ash::vk::Rect2D {
            offset: ash::vk::Offset2D { x: 0, y: 0 },
            extent,
        };

        unsafe {
            self.device
                .get_device()
                .cmd_set_viewport(command_buffer.get_handle(), 0, &viewport)
        };
        unsafe {
            self.device
                .get_device()
                .cmd_set_scissor(command_buffer.get_handle(), 0, &[scissors])
        };

        let clear_values = clear_colors
                .iter()
                .map(|color| ash::vk::ClearValue::from(*color))
                .collect::<Vec<_>>();

        let begin_info = ash::vk::RenderPassBeginInfo::builder()
            .render_pass(self.render_pass)
            .framebuffer(self.handle)
            .render_area(scissors)
            .clear_values(&clear_values)
            .build();

        unsafe {
            self.device.get_device().cmd_begin_render_pass(
                command_buffer.get_handle(),
                &begin_info,
                ash::vk::SubpassContents::INLINE,
            )
        };
    }
```

When opt-level is greater than 0, the last function, cmd_begin_render_pass, generates a segfault. There are no validation layer errors, and the faulty address is 0x12c, which i assume is just indexing into a null pointer. This segfault comes from the internals of the vulkan driver. I've seen that there are other issues similar to this, where the error is some pointer/array slice being optimized out, but i dont see where this could be happening in my code. I've also dumped the memory of the begin info in both cases, and it seems correct both times, just the pointers being slightly different. Can someone help me with this?

**Comment by MarijnS95** [comment]
First and foremost, [per the `README`](https://github.com/ash-rs/ash/tree/0.37.3?tab=readme-ov-file#builder-pattern), I recommend calling `.build()` as few times as possible, in this case not on `RenderPassBeginInfo`, so that no lifetime info is dropped. This function will be removed entirely in the impending `0.38` release of `ash` for exactly this reason.

Other than that there doesn't seem to be any inherent problem with this implementation, but it is possible that it originates from elsewhere in your implementation where `.build()` is called and Vulkan was given pointers to invalid information. Please use the readme to see if you can remove more `.build()` calls from elsewhere to uncover the problem.

**Comment by mqxf** [comment]
Yep, that worked, it was a different builder somewhere else, I am unsure where since I removed them all at once.
