### ISSUE TITLE
Using `get_query_pool_results` with `vk::QueryResultFlags::WITH_AVAILABILITY` flag

### ISSUE THREAD

**Issue by YouSafe** [ash-rs/ash#900]
Currently `get_query_pool_results` assumes a stride of `mem::size_of::<T>() as _`, however, when using `vk::QueryResultFlags::WITH_AVAILABILITY` the stride should I think be double that to account for the availability bit.

**Comment by YouSafe** [comment]
This also holds for the `VK_QUERY_RESULT_WITH_STATUS_BIT_KHR` flag.

See note from the specification:
> Note:  If `VK_QUERY_RESULT_WITH_AVAILABILITY_BIT` or `VK_QUERY_RESULT_WITH_STATUS_BIT_KHR` is set, the layout of data in the buffer is a (result,availability) or (result,status) pair for each query returned, and stride is the stride between each pair.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetQueryPoolResults.html#_description

**Comment by MarijnS95** [comment]
@YouSafe we've covered this in https://github.com/ash-rs/ash/issues/100#issuecomment-1530041456, https://github.com/ash-rs/ash/issues/639#issuecomment-1432767800 and #644: use a tuple (or likewise `repr(C)` type) to receive the boolean. The advantage is that the `T` type immediately incorporates the status or availability bit (how else would you receive that with this function, otherwise?).

Closing as duplicate.

**Comment by YouSafe** [comment]
I incorrectly assumed that T should only be a primitive such as u32 or u64, when a pair would also work and provide the correct stride.

Apologies for this oversight.
