### ISSUE TITLE
Raytrace pipeline creation fails only on release build

### ISSUE THREAD

**Issue by ktmattson-alion** [ash-rs/ash#926]
I am using ash v37, but I don't see much connection between the changelog and this problem so I'm waiting to deal with the breaking changes unless someone can confirm that this is a problem particular to v37.

I have a pretty uncomplicated ray trace pipeline, and my program works fine in its debug build. But if I run the release target, I get a crash with an Access Violation error, and this in the Vulkan validation layer:

        [0] 0x26e4786ee90, type: 1, name: NULL
VUID-VkPipelineShaderStageCreateInfo-sType-sType(ERROR / SPEC): msgNum: 1451162469 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-sType-sType ] Object 0: handle = 0x26e58d68060, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x567efb65 | vkCreateRayTracingPipelinesKHR: parameter pCreateInfos[0].pStages[0].sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-sType-sType)
    Objects: 1
        [0] 0x26e58d68060, type: 3, name: NULL
VUID-VkPipelineShaderStageCreateInfo-sType-sType(ERROR / SPEC): msgNum: 1451162469 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-sType-sType ] Object 0: handle = 0x26e58d68060, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x567efb65 | vkCreateRayTracingPipelinesKHR: parameter pCreateInfos[0].pStages[1].sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-sType-sType)
    Objects: 1
        [0] 0x26e58d68060, type: 3, name: NULL
VUID-VkPipelineShaderStageCreateInfo-sType-sType(ERROR / SPEC): msgNum: 1451162469 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-sType-sType ] Object 0: handle = 0x26e58d68060, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x567efb65 | vkCreateRayTracingPipelinesKHR: parameter pCreateInfos[0].pStages[2].sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-sType-sType)
    Objects: 1
        [0] 0x26e58d68060, type: 3, name: NULL
VUID-VkPipelineShaderStageCreateInfo-pNext-pNext(ERROR / SPEC): msgNum: -768403575 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-pNext-pNext ] Object 0: handle = 0x26e58d68060, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd2331789 | vkCreateRayTracingPipelinesKHR: pCreateInfos[0].pStages[0].pNext chain includes a structure with unknown VkStructureType (1221626185); Allowed structures are [VkPipelineShaderStageRequiredSubgroupSizeCreateInfo]. This error is based on the Valid Usage documentation for version 204 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case the use of pCreateInfos[0].pStages[0].pNext is undefined and may not work correctly with validation enabled The Vulkan spec states: pNext must be NULL or a pointer to a valid instance of VkPipelineShaderStageRequiredSubgroupSizeCreateInfo (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-pNext-pNext)
    Objects: 1
        [0] 0x26e58d68060, type: 3, name: NULL

As far as I can trace things, `s_type` _is_ VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO (what else could it be?) Do you have any insight why this is happening?

**Comment by MarijnS95** [comment]
@ktmattson-alion this sounds a lot like you're creating memory corruption, such as referring to a stack-local piece of memory that been "deallocated", or overwritten in a loop. Thanks to pointer magic and perhaps accidentally calling `.build()`, Rust's borrow checker is no longer able to validate that your code is safe (and is one of the reasons why all raw Vulkan calls and pointer dereferences in general are marked `unsafe`).

This is exactly what the `ash 0.38` release is preventing, by removing `.build()` and no longer allowing users to _discard the lifetime of Vulkan structs containing pointers to elsewhere within their Rust program_. I strongly urge you to bite the bullet and upgrade, as it will help you point out exactly where this issue is occurring in your code at compile time (assuming you use the builder pattern/API, and not accessing raw fields with pointer coercion or casting).

---

If that doesn't help, you should share a snippet of all this struct-construction code leading up to `vkCreateRayTracingPipelinesKHR()` so that we can have a look.

**Comment by ktmattson-alion** [comment]
That sounds plausible, and in fact, while I use the deref pattern rather than `build()` for the most part for this very reason, here I had been calling `build` on the final struct. Moving that into the deref pattern fixed the issue.

I guess the reason this happens for the release target is that optimizations mess with pointer magic that worked in the debug build.

I appreciate the work you've all put into this latest release, and I will go shave the yak; I just wanted to make sure that I didn't go into that time sink and come out the other end with the same bug 😄 Also, thank you for the quick response.

**Comment by MarijnS95** [comment]
> here I had been calling `build` on the final struct. Moving that into the deref pattern fixed the issue.

Just curious: did the compiler point out an apparent lifetime issue after changing to `Deref`?

> I guess the reason this happens for the release target is that optimizations mess with pointer magic that worked in the debug build.

Typically the `dev` profile keeps things alive for longer, which is actually a bit unfortunate here because people generally expect (if there's not too much `unsafe` around) for their application to work & behave in the exact same way in a release build, which you found out the hard way it doesn't.

---

Glad you figured it out quickly, and good luck with the migration! Besides extension module renaming, it shouldn't be all too terrible after removing `.build()` and replacing `s/::builder()/::default()/` :+1:

**Comment by filnet** [comment]
> Glad you figured it out quickly, and good luck with the migration! Besides extension module renaming, it shouldn't be all too terrible after removing `.build()` and replacing `s/::builder()/::default()/` and `s/::name()/::NAME` 👍

I migrated one or two projects and it was a smooth ride.
See https://github.com/adrien-ben/imgui-rs-vulkan-renderer/pull/41/files

**Comment by ktmattson-alion** [comment]
> Just curious: did the compiler point out an apparent lifetime issue after changing to `Deref`?

It did in this way, the code that did not work was like so:
`
             let pipeline_create_info = vk::RayTracingPipelineCreateInfoKHR::builder()
                .stages(&[*rgen_stage_info, *rmiss_stage_info, *rchit_stage_info])
                .groups(&[*rgen_group_info, *rmiss_group_info, *rchit_group_info])
                .layout(pipeline_layout)
                .flags(vk::PipelineCreateFlags::empty())
                .max_pipeline_ray_recursion_depth(2)
                .build();
`
And in order to use Deref on `pipeline_create_info`, the stages and groups had to be moved into their own array, or else borrow checker would warn about the temporary reference. In retrospect, that seems like an obvious red flag--all that build() did was paper over the borrow checker's error--but there it is.
